services:
  aidd:
    build: ./aidd
    volumes:
      - ./aidd/src:/home/app
      - ./volumes/code:${PROJECT_DIR}
      - ./volumes/template:${TEMPLATE_DIR}
      - ./volumes/logs:/logs
    env_file: .env
    command: >
      watchmedo auto-restart
        --directory=/home/app
        --pattern=*.py
        --recursive
        --no-restart-on-command-exit
        -- python main.py
